# Generated by Django 4.1.3 on 2022-11-21 13:50

import PetPalStories.core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Petition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(10, message='You are supposed to enter at least 10 characters')])),
                ('location', models.CharField(blank=True, choices=[('Local', 'Local'), ('National', 'National'), ('Worldwide', 'Worldwide')], default='Local', max_length=9)),
                ('goal', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10, message='You are supposed to set your goal to minimum 10 signatures')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='petitions_images/', validators=[PetPalStories.core.validators.validate_image_size])),
                ('published_on', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-published_on',),
                'unique_together': {('title', 'id')},
            },
        ),
    ]
