# Generated by Django 4.1.3 on 2022-11-21 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='petition',
            name='goal',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10, message='You are supposed to set your goal to minimum of 10 signatures')]),
        ),
    ]
