# Generated by Django 4.1.3 on 2022-11-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0002_petition_is_active_alter_petition_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='location',
            field=models.CharField(blank=True, choices=[('Local', 'Local'), ('National', 'National'), ('Europe', 'Europe'), ('Worldwide', 'Worldwide')], default='Local', max_length=9),
        ),
    ]
