# Generated by Django 4.1.3 on 2022-11-26 12:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0003_alter_petition_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
