# Generated by Django 4.1.3 on 2022-11-10 15:44

import PetPalStories.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appUser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), PetPalStories.core.validators.validate_only_letters], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), PetPalStories.core.validators.validate_only_letters], verbose_name='Last Name'),
        ),
    ]
