# Generated by Django 4.1.3 on 2022-11-28 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, message='You are supposed to enter at least 10 characters')]),
        ),
    ]
