# Generated by Django 4.1.3 on 2022-11-08 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('pet_name', models.CharField(max_length=20)),
                ('pet_species', models.CharField(blank=True, choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird'), ('Fish', 'Fish'), ('Lizard', 'Lizard'), ('Snake', 'Snake'), ('Other', 'Other')], default='Other', max_length=6, null=True)),
                ('text', models.TextField(validators=[django.core.validators.MinLengthValidator(10, message='You are supposed to enter at least 10 characters')])),
                ('published_on', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
