# Generated by Django 4.1.3 on 2022-11-08 14:49

import PetPalStories.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='picture',
            field=models.ImageField(blank=True, default='Pet Image', null=True, upload_to='pet_photos/', validators=[PetPalStories.core.validators.validate_image_size]),
        ),
    ]
