# Generated by Django 4.1.3 on 2022-11-16 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_story_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ('-published_on',), 'verbose_name_plural': 'Stories'},
        ),
    ]
