# Generated by Django 4.1.3 on 2022-11-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_story_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='pet_name',
            field=models.CharField(max_length=20, verbose_name='Pet Name'),
        ),
        migrations.AlterField(
            model_name='story',
            name='pet_species',
            field=models.CharField(blank=True, choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird'), ('Fish', 'Fish'), ('Lizard', 'Lizard'), ('Snake', 'Snake'), ('Other', 'Other')], default='Other', max_length=6, null=True, verbose_name='Pet Species'),
        ),
    ]
