# Generated by Django 4.1.3 on 2022-11-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_story_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='story',
            unique_together={('title', 'id')},
        ),
    ]
