# Generated by Django 4.1.3 on 2022-11-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_alter_story_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='pet_name',
            field=models.CharField(max_length=15, verbose_name='Pet Name'),
        ),
    ]
