# Generated by Django 4.1.3 on 2022-11-11 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='user',
            new_name='owner',
        ),
    ]
