# Generated by Django 4.1.3 on 2022-11-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_user_favourite_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='owner',
            new_name='sender',
        ),
    ]
