# Generated by Django 4.1.3 on 2022-11-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_messagestory_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagestory',
            name='seen_on',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
