# Generated by Django 4.1.3 on 2022-11-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_messagestory_seen_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favouritestory',
            old_name='owner',
            new_name='user',
        ),
    ]
