# Generated by Django 4.1.3 on 2022-11-21 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_rename_owner_favouritestory_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favouritestory',
            options={'verbose_name_plural': 'Favourite Stories'},
        ),
        migrations.AlterModelOptions(
            name='messagestory',
            options={'ordering': ('-sent_on',), 'verbose_name_plural': 'Message Stories'},
        ),
    ]
