# Generated by Django 4.1.3 on 2022-11-22 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0003_alter_petition_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0010_alter_favouritestory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedPetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_on', models.DateTimeField(auto_now_add=True)),
                ('petition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='petitions.petition')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-signed_on',),
            },
        ),
    ]
