# Generated by Django 4.1.3 on 2022-11-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_signedpetition'),
    ]

    operations = [
        migrations.AddField(
            model_name='signedpetition',
            name='is_agreed',
            field=models.BooleanField(default=False, verbose_name='Personal data terms and conditions'),
        ),
    ]
