# Generated by Django 4.1.3 on 2022-11-22 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petitions', '0003_alter_petition_location'),
        ('common', '0012_signedpetition_is_agreed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signedpetition',
            name='is_agreed',
            field=models.BooleanField(verbose_name='Personal data terms and conditions: '),
        ),
        migrations.AlterUniqueTogether(
            name='signedpetition',
            unique_together={('user', 'petition')},
        ),
    ]
