# Generated by Django 4.1.3 on 2022-12-14 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petitions', '0007_alter_petition_image'),
        ('common', '0014_alter_messagestory_sender_alter_messagestory_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagestory',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='signedpetition',
            name='petition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='petitions.petition'),
        ),
        migrations.AlterField(
            model_name='signedpetition',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
